### ISSUE TITLE
Add Event for commit from gui

### ISSUE THREAD

**Issue by jermophats** [atlassian-labs/atlassian-slack-integration-server#113]
Hi Atlassian Labs,
The Slack plugin for Bitbucket (on Data Center 7.6.4 does not handle an event for a commit from the gui

This does not count as a RepositoryPushEvent, but I think instead is a RepositoryRefsChangedEvent
https://docs.atlassian.com/bitbucket-server/javadoc/7.12.1/api/com/atlassian/bitbucket/event/repository/RepositoryPushEvent.html

As it. stands it does not seem there is a bitbucket event directly related
only the following types of events are considered:

RepositoryForkedEvent.class --> RepositoryNotificationTypes.FORKED
RepositoryPushEvent.class --> RepositoryNotificationTypes.PUSHED
TagCreatedEvent.class --> RepositoryNotificationTypes.TAG_CREATED
TagDeletedEvent.class --> RepositoryNotificationTypes.TAG_DELETED
BranchCreatedEvent.class --> RepositoryNotificationTypes.BRANCH_CREATED
BranchDeletedEvent.class --> RepositoryNotificationTypes.BRANCH_DELETED
CommitDiscussionCommentAddedEvent.class --> RepositoryNotificationTypes.COMMENT_ADDED
CommitDiscussionCommentEditedEvent.class --> RepositoryNotificationTypes.COMMENT_EDITED
CommitDiscussionCommentRepliedEvent.class --> RepositoryNotificationTypes.COMMENT_REPLIED
CommitDiscussionCommentDeletedEvent.class --> RepositoryNotificationTypes.COMMENT_DELETED

In this particular instance - the act of adding a commit to Bitbucket through the front-end does not count as a "push" but only a commit. This means that although it's going to trigger the 'RepositoryRefsChanged' event, it's going to not match the expected 'RepositoryPushEvent' that will actually trigger a notification with the Slack plugin. And this is intended if we review the 'RepositoryPushEvent' information from the development API:

Event that is raised when a user pushes one or more refs to a repository. A push does not guarantee that new commits have been added to the repository; it only guarantees at least one ref has been changed.

Listeners that are interested in all ref changes, not just those stemming from pushes (such as pull request merges), should listen for RepositoryRefsChangedEvents instead.

Thanks!
Jeremy Capps Hermes
SiriusXM+Pandora Atlassian Support

**Comment by bturner** [comment]
Bitbucket Server developer here. I suspect the mapping that's missing is for [`FileEditedEvent`](https://docs.atlassian.com/bitbucket-server/javadoc/7.17.1/api/com/atlassian/bitbucket/event/content/FileEditedEvent.html). That's in-browser editing. I think it probably shouldn't be mapped to `PUSHED`, since it's not a push, but I'm happy to leave that to whoever does the work to decide. I'm just trying to help point out the event to map, because you can't map this from a straight `RepositoryRefsChangedEvent` (which, I'll note, [is already what the plugin listens for](https://github.com/atlassian-labs/atlassian-slack-integration-server/blob/master/bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/listener/BitbucketNotificationEventListener.java#L141-L142)), because _every_ event that modifies refs implements that interface.

**Comment by mvlasovatl** [comment]
The fix was implemented in #193 and merged to `dev`. It will be included into next plugin release.

**Comment by mvlasovatl** [comment]
The fix was included into Bitbucket Server for Slack 4.0.3.
