### ISSUE TITLE
Changes to Slack Events API (authorizations instead of authed_users/authed_teams)

### ISSUE THREAD

**Issue by onitake** [atlassian-labs/atlassian-slack-integration-server#59]
Slack announced that there are some changes coming to the Events API: https://api.slack.com/changelog/2020-09-15-events-api-truncate-authed-users

Quote:
> Event payloads will no longer contain a full list of authed_users or authed_teams. These two fields will be deprecated. There'll be a new, compact field called authorizations to replace them—but authorizations will only contain at most one person or workspace that the event is visible to.
>
> If you need a full list of all the parties an event is visible to, you'll call the apps.event.authorizations.list method.

Does this affect the JIRA/Confluence server integration?
If yes, changes may be needed.

**Comment by utluiz** [comment]
Thank you for the call out. While that change will affect Server apps in the sense they will have the new payloads coming in, we don't think that's going to break the apps as we don't use such fields. But we'll perform some tests to confirm that.

**Comment by ward-minnis-ix** [comment]
Hi! Got the same notice about the deprecation but also see the Jira and Confluence apps listed in the deprecation tool 
<img width="978" alt="slack and jira" src="https://user-images.githubusercontent.com/73170357/96575849-4a43f600-129f-11eb-85e2-391b0114bb55.png">

**Comment by mvlasovatl** [comment]
Hey guys! Could you provide ID of the affected Slack workspaces so that we could provide them to Slack to investigate this issue?

**Comment by utluiz** [comment]
Hi y'all!

Our team has confirmed the Server Apps for Jira, Bitbucket, and Confluence are prepared for those Slack API changes. They will continue to work normally.

We have also communicated with Slack and they confirmed the deprecation notice should not have been displayed for the Server Apps, at least when the **simplified installation** method is used, which uses a special type of App. If you are seeing such Apps listed in the breaking changes list, it’s a bug on the Slack side. You're encouraged to reach out to Slack directly since they - and not Atlassian - have control over that list (all we could do is tell Slack about it).

Note there's an exception to the above. If you have chosen the **advanced installation method**, the one that involves manually creating a custom Slack App, you should perform the API upgrade yourself in the Slack App settings (https://api.slack.com/apps) as advised by Slack.
